### ISSUE TITLE
new docker 1.9+ multihost docker networking

### ISSUE THREAD

**Issue by a93ushakov** [gondor/depcon#3]
http://blog.docker.com/2015/11/docker-multi-host-networking-ga/
After 1.9 release docker supports 'docker network create'  command. 

Is it possible to rollout several docker containers in one network with depcon?

**Comment by gondor** [comment]
I don't think this would be hard to add support for.  Are you using Mesos/Marathon as your scheduler?

**Comment by a93ushakov** [comment]
Yes, I use Apache Mesos + marathon.

**Comment by gondor** [comment]
I'm not sure how you could pre-execute the `docker network create` within Marathon.  This is a current limitation of Marathon and not Depcon.  If the network is already created you could associate instances by adding the following to your service descriptor and deploying it via Depcon.

Lets assume we have a network pre-created called `isolated_nw`

```
docker network create --driver bridge isolated_nw
```

Using Depcon to launch a new container in Marathon referring to the network with the service descriptor below:
```
id: test-network
cpus: 0.6
mem: 200
instances: 1
container:
  docker:
    image: ubuntu
    network: BRIDGE
    parameters:
    - key: net
      value: isolated_nw
    portMappings:
    - containerPort: 8711
      hostPort: 0
      protocol: tcp
  type: DOCKER
```

Hope that helps
